spring:
  application:
    name: ai-code-friends
server:
  port: 8081
  servlet:
    context-path: /api

langchain4j:
 community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: sk-0383bdf53c324a8c922df9b6af4cf10a

